### ISSUE TITLE
Dotnet quits if it doesn't recognize a mapped resource

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-sdk-dotnet#210]
Hey Nate!

I didn't see this as an open issue, so I wanted to post this here. Feel free to close if it's a dupe. When I have a SAML directory mapped to my Application and try to run the ASP.NET Core sample project, dotnet quits before startup with the following error. (In other sdks/integrations, the server starts up but just doesn't show the SAML buttons, which I expect). 

```
StormpathExample $ dotnet run
Project StormpathExample (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
info: StormpathMiddleware[0]
      StormpathMiddleware Stormpath middleware starting up
info: StormpathMiddleware[0]
       No CacheProvider configured. Defaulting to in-memory CacheProvider with default TTL and TTI of one hour.
info: StormpathMiddleware[0]
      InitializeClient Using tenant real-flier
info: StormpathMiddleware[0]
      EnsureApplication Using Stormpath application 'GoogleAppTester' (https://api.stormpath.com/v1/applications/6D4hvpvZX9kECMTuGd0ufS)
warn: StormpathMiddleware[0]
       Can not cache array 'emailDomainWhitelist'. Item type for 'IAccountCreationPolicy' unknown. 'https://api.stormpath.com/v1/accountCreationPolicies/6D5PAMrP4GSJxahFyH3FrG' will not be cached.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: No type mapping could be found for this resource.
   at Stormpath.SDK.Impl.DataStore.DefaultDataStore.Stormpath.SDK.Impl.DataStore.IInternalSyncDataStore.GetResource[T](String href, Func`2 typeLookup)
   at Stormpath.SDK.Impl.Directory.DefaultDirectory.Stormpath.SDK.Impl.Directory.IDirectorySync.GetProvider()
   at Stormpath.SDK.Sync.SyncDirectoryExtensions.GetProvider(IDirectory directory)
   at Stormpath.Owin.Middleware.StormpathMiddleware.<GetSocialProviders>d__30.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stormpath.Owin.Middleware.StormpathMiddleware.GetIntegrationConfiguration(IClient client, StormpathConfiguration updatedConfiguration, ILogger logger)
   at Stormpath.Owin.Middleware.StormpathMiddleware.Create(StormpathOwinOptions options)
   at Stormpath.AspNetCore.StormpathMiddlewareExtensions.UseStormpath(IApplicationBuilder app)
   at StormpathExample.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at StormpathExample.Program.Main(String[] args)
```

**Comment by nbarbettini** [comment]
This was fixed a few days ago 😄 See https://github.com/stormpath/stormpath-sdk-dotnet/issues/208. The [Stormpath.SDK 0.94.1](https://www.nuget.org/packages/Stormpath.SDK/0.94.1) package (or later) will not error in this scenario.

The ASP.NET Core example project will be updated to the latest release shortly!

**Comment by nbarbettini** [comment]
Updated example via https://github.com/stormpath/stormpath-aspnetcore-example/commit/000b7ba9899d823906e51f934801c57406282054
